id: P4A366CDD
initial_creation_type: input
source_metadata:
  Title: Piṇḍīkramaḥ Pañcakrama
  Editor: Ram Shankar Tripthi
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '2001'
  Piṇḍīkramaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:58:53.907820'
last_modified_at: '2022-03-08T16:58:53.907829'
